---
- name: POC Compute Image Provisioning
  hosts: localhost
  tasks:
    - name: Print Status Message
      ansible.builtin.debug:
        msg: "Successfully executed Ansible playbook from the embedded Submodule folder!"
